@host = http://localhost:3000

### Cria produto

POST {{host}}/api/produtos
Content-Type: application/json
{
    "nome": "Computador",
    "preco": 5600.99,
    "quantidade": 100
}

##Listar

GET {{host}}/api/produtos

### Obter pro ID

GET {{host}}/api/produtos/___________

###Atualizar

PUT {{host}}/api/produtos/___________

Content-Type: application/json
{
    "preco": 6600.99
}

### Deletar
DELETE {{host}}/api/produtos/___________